### ISSUE TITLE
sending messages over websocket

### ISSUE THREAD

**Issue by toastxc** [ktwrd/RevSharp#1]
is there currently any way to send data back over WS? if not is this planned for future.

**Comment by ktwrd** [comment]
You can, it's accessible via [`WebsocketClient.SendMessage(T data)`](https://github.com/ktwrd/RevSharp/blob/main/RevSharp.Core/WebsocketClient.cs#L210) and you can access an instance of that on the `WSClient` field of `Client`.

But it's an internal method at the moment. I could expose it via Client like `Client.SendWebsocket(T data)` but only allow types that extend the [BaseTypedResponse](https://github.com/ktwrd/RevSharp/blob/main/RevSharp.Core/Models/BaseTypedResponse.cs#L8) class (since that's all that's allowed to send to bonfire afik)

**Comment by toastxc** [comment]
thanks
i encountered issues with splitstream/sink with websocket but if you've figured that out thats really good
